name = "tct-chain"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[assets]
directory = "./dist"
binding = "ASSETS"

[[routes]]
pattern = "torn.nobaggage2rome.com"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "tct-db"
database_id = "771396e6-dd72-41cb-87da-64f5565c8cce"

[[kv_namespaces]]
binding = "TCT_CACHE"
id = "cd04cc35dccb4aca92098677815d7128"

[[queues.producers]]
queue = "tct-member-queue"
binding = "MEMBER_QUEUE"

[[queues.consumers]]
queue = "tct-member-queue"
max_batch_size = 10
max_batch_timeout = 5

[[durable_objects.bindings]]
name = "CHAIN_MONITOR"
class_name = "ChainMonitor"

[[migrations]]
tag = "v1"
new_classes = ["ChainMonitor"]

[vars]
FACTION_ID = "12345" # TODO: 填写真实的帮派 ID
